version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "3001:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

volumes: 
  pgdata: